# Generated by Django 4.2.15 on 2025-01-25 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0005_computerproficiency_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingExpereince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('start_date', models.CharField(max_length=225)),
                ('end_date', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.jobtitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_expereince', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportingDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='static/supportindocuments/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=6, null=True)),
                ('salary', models.CharField(max_length=225, null=True)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=6, null=True)),
                ('idnumber', models.CharField(max_length=13)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.CharField(max_length=6)),
                ('dob', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.softproficiency')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.softskillslist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=100, null=True)),
                ('start_time', models.CharField(max_length=225)),
                ('end_time', models.CharField(max_length=225)),
                ('working_hours', models.CharField(max_length=225)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225, null=True)),
                ('phone', models.CharField(max_length=225, null=True)),
                ('position', models.CharField(max_length=60, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to=settings.AUTH_USER_MODEL)),
                ('working_experince', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_exp', to='profiles.workingexpereince')),
            ],
        ),
        migrations.CreateModel(
            name='Raise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=225)),
                ('amount', models.CharField(max_length=225)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=225)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/profiles/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=13, unique=True)),
                ('phone', models.CharField(default=' ', max_length=10, null=True)),
                ('dob', models.CharField(max_length=6)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.CharField(max_length=6)),
                ('maritial_status', models.CharField(default=' ', max_length=10)),
                ('race', models.CharField(default=' ', max_length=15)),
                ('disability', models.CharField(default=' ', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('linkedin_profile', models.CharField(default=' ', max_length=225)),
                ('personal_website', models.CharField(default=' ', max_length=225)),
                ('cover_letter', models.CharField(default=' ', max_length=225)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lave_type', models.CharField(max_length=225)),
                ('message', models.CharField(max_length=225)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=225)),
                ('seen', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.languagelist')),
                ('reading_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.readingproficiencylist')),
                ('speaking_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.speakingproficiencylist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('writing_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.writingproficiencylist')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=225, null=True)),
                ('end_date', models.CharField(max_length=225, null=True)),
                ('status', models.CharField(max_length=225, null=True)),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.qualification')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.institution')),
                ('nqf_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.nqf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.computerproficiency')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.computerskillslist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.CharField(max_length=225, null=True)),
                ('is_late', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=225)),
                ('active', models.CharField(default='Inactive', max_length=225, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.shift')),
            ],
        ),
        migrations.CreateModel(
            name='AddressInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_line', models.CharField(max_length=225, null=True)),
                ('city', models.CharField(max_length=225, null=True)),
                ('province', models.CharField(max_length=225, null=True)),
                ('postal_code', models.CharField(max_length=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
