# Generated by Django 4.2.11 on 2024-06-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinformation',
            name='city',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='addressinformation',
            name='postal_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='addressinformation',
            name='province',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='addressinformation',
            name='street_address_line',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
