# Generated by Django 4.2.15 on 2025-02-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_staffprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='dob',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
