# Generated by Django 4.2.11 on 2024-06-18 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=6, null=True)),
                ('salary', models.CharField(max_length=225, null=True)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=6, null=True)),
                ('idnumber', models.CharField(max_length=13)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.CharField(max_length=6)),
                ('dob', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
