# Generated by Django 4.2.11 on 2024-06-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_shift_raise_leave_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.CharField(default=' ', max_length=225),
            preserve_default=False,
        ),
    ]
