# Generated by Django 4.2.11 on 2024-06-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_shift_end_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='working_hours',
            field=models.CharField(default='8', max_length=225),
            preserve_default=False,
        ),
    ]
