# Generated by Django 4.2.11 on 2024-06-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_shift_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
