# Generated by Django 4.2.11 on 2024-06-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_leave_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='late',
            new_name='minutes',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.CharField(default='Inactive', max_length=20),
        ),
    ]
