# Generated by Django 4.2.11 on 2024-06-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_late_attendance_minutes_attendance_is_late_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='active',
            field=models.CharField(default='Inactive', max_length=225, null=True),
        ),
    ]
