# Generated by Django 4.2.11 on 2024-06-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinformation',
            name='town',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
