# Generated by Django 4.2.11 on 2024-06-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_addressinformation_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressinformation',
            name='town',
        ),
    ]
