# Generated by Django 4.2.11 on 2024-06-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_remove_addressinformation_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disability',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='maritial_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='race',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
