# Generated by Django 4.2.11 on 2024-07-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_disability_profile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_profile',
            field=models.CharField(default=' ', max_length=225),
            preserve_default=False,
        ),
    ]
