# Generated by Django 4.2.11 on 2024-07-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_linkedin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_website',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
