# Generated by Django 4.2.14 on 2024-07-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_computerskills_user_alter_language_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='status',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='field_of_study',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='highest_qualification',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='year_obtained',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
