# Generated by Django 4.2.14 on 2024-09-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_computerskills_user_alter_language_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='proficiency',
            new_name='reading_proficiency',
        ),
        migrations.AddField(
            model_name='language',
            name='speaking_proficiency',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='writing_proficiency',
            field=models.CharField(default=' ', max_length=225),
            preserve_default=False,
        ),
    ]
