# Generated by Django 4.2.15 on 2024-09-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_supportingdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(default=' ', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='disability',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_profile',
            field=models.CharField(default=' ', max_length=225),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maritial_status',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_website',
            field=models.CharField(default=' ', max_length=225),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=' ', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
