# Generated by Django 4.2.15 on 2024-09-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_profile_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verification_token',
        ),
    ]
