# Generated by Django 4.2.15 on 2024-09-16 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0001_initial'),
        ('profiles', '0028_remove_profile_verification_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='highest_qualification',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='year_obtained',
            new_name='nqf_level',
        ),
        migrations.RemoveField(
            model_name='computerskills',
            name='level',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='softskills',
            name='level',
        ),
        migrations.AddField(
            model_name='computerskills',
            name='proficiency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.computerproficiency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='start_date',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='softskills',
            name='proficiency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.softproficiency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computerskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.computerskillslist'),
        ),
        migrations.AlterField(
            model_name='computerskills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.languagelist'),
        ),
        migrations.AlterField(
            model_name='language',
            name='reading_proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.readingproficiencylist'),
        ),
        migrations.AlterField(
            model_name='language',
            name='speaking_proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.speakingproficiencylist'),
        ),
        migrations.AlterField(
            model_name='language',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='language',
            name='writing_proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.writingproficiencylist'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='field_of_study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.qualification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='softskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.softskillslist'),
        ),
        migrations.AlterField(
            model_name='workingexpereince',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.jobtitle'),
        ),
    ]
