# Generated by Django 4.2.15 on 2024-09-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_nqf'),
        ('profiles', '0029_rename_highest_qualification_qualification_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='nqf_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.nqf'),
            preserve_default=False,
        ),
    ]
