# Generated by Django 4.2.15 on 2024-09-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_usersprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersProfile',
        ),
    ]
