# Generated by Django 4.2.15 on 2024-09-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_delete_usersprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.addressinformation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='computer_skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.computerskills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.language'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.profileimage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.qualification'),
        ),
        migrations.AddField(
            model_name='profile',
            name='soft_skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.softskills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.supportingdocuments'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_experience',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.workingexpereince'),
        ),
    ]
