# Generated by Django 4.2.15 on 2024-09-17 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_nqf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0030_alter_qualification_nqf_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qualification',
            new_name='Education',
        ),
    ]
