# Generated by Django 4.2.15 on 2024-09-19 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0031_rename_qualification_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingexpereince',
            old_name='years_of_expreince',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='addressinformation',
            name='street_address_line1',
        ),
        migrations.AlterField(
            model_name='addressinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
    ]
