# Generated by Django 4.2.15 on 2024-09-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_profile_name_profile_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disability',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_profile',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maritial_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_website',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='race',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
