# Generated by Django 4.2.15 on 2024-09-20 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0033_profile_cover_letter_alter_workingexpereince_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225, null=True)),
                ('phone', models.CharField(max_length=225, null=True)),
                ('position', models.CharField(max_length=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to=settings.AUTH_USER_MODEL)),
                ('working_experince', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_exp', to='profiles.workingexpereince')),
            ],
        ),
    ]
