# Generated by Django 4.2.11 on 2024-06-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
