# Generated by Django 4.2.11 on 2024-06-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_academic_job_post_alter_experience_job_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.CharField(max_length=225),
        ),
    ]
