# Generated by Django 4.2.11 on 2024-06-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_experience_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(default='wating', max_length=20),
        ),
    ]
