# Generated by Django 4.2.15 on 2024-08-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_jobapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, null=True)),
                ('level', models.CharField(max_length=15, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
