# Generated by Django 4.2.15 on 2024-09-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_skillvalidation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_id',
            new_name='job',
        ),
    ]
