# Generated by Django 4.2.15 on 2024-09-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_job', to='jobs.jobpost'),
        ),
    ]
