# Generated by Django 4.2.11 on 2024-09-09 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0018_skilllist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_required', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Fluent', 'Fluent')], max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.languagelist')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_proficiency', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Fluent', 'Fluent')], max_length=10)),
                ('writing_proficiency', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Fluent', 'Fluent')], max_length=10)),
                ('speaking_proficiency', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Fluent', 'Fluent')], max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.languagelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
