# Generated by Django 4.2.15 on 2024-09-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_alter_interview_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.CharField(max_length=225),
        ),
    ]
