# Generated by Django 4.2.15 on 2024-09-09 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0020_alter_interview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='job',
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='jobs.jobapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
