# Generated by Django 4.2.11 on 2024-09-11 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0022_alter_interview_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_date', models.DateTimeField(auto_now_add=True)),
                ('reason_for_closure', models.CharField(max_length=255)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_histories', to='jobs.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_proficiency', models.CharField(choices=[('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good')], max_length=10)),
                ('writing_proficiency', models.CharField(choices=[('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good')], max_length=10)),
                ('speaking_proficiency', models.CharField(choices=[('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good')], max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.languagelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_required', models.CharField(choices=[('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good')], max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.languagelist')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost')),
            ],
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='job_post',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='job_post',
        ),
        migrations.DeleteModel(
            name='SkillValidation',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
