# Generated by Django 4.2.15 on 2024-09-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='application',
        ),
        migrations.AddField(
            model_name='feedback',
            name='job',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost'),
            preserve_default=False,
        ),
    ]
