# Generated by Django 4.2.15 on 2024-09-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_rename_jobs_feedback_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company_name',
        ),
    ]
