# Generated by Django 4.2.15 on 2024-09-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_computerskill_softskill_remove_academic_level_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='jobapplication',
            name='filterd_out',
            field=models.BooleanField(default=False),
        ),
    ]
