# Generated by Django 4.2.15 on 2024-09-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_language_delete_skillvalidation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillValidation',
        ),
    ]
