# Generated by Django 4.2.15 on 2024-09-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_delete_skillvalidation'),
    ]

    operations = [
      
    ]
