# Generated by Django 4.2.15 on 2024-10-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_delete_skillvalidation'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='jobapplication',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
