# Generated by Django 4.2.15 on 2024-10-15 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0034_delete_skillvalidation_jobapplication_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='current_stage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='previous_stage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
