# Generated by Django 4.2.15 on 2024-10-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_delete_skillvalidation_quiz_is_active'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='quizresults',
            name='total',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
