# Generated by Django 4.2.15 on 2024-10-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_delete_skillvalidation_jobapplication_is_filter_and_more'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='jobapplication',
            name='reason',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
