# Generated by Django 4.2.15 on 2025-01-25 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0043_delete_skillvalidation_jobpost_hide_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.quizresults')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
        
    ]
