# Generated by Django 4.2.15 on 2025-01-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_quizanswers_delete_skillvalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswers',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.quiz'),
        ),
    ]
