# Generated by Django 4.2.15 on 2025-02-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_delete_skillvalidation_alter_quizanswers_quiz'),
    ]

    operations = [
        
    ]
