# Generated by Django 4.2.15 on 2025-02-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_delete_skillvalidation'),
    ]

    operations = [
       
    ]
