# Generated by Django 4.2.15 on 2025-02-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0048_alert_delete_skillvalidation_jobpost_current_step'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(default='pending', max_length=250),
        ),
    ]
