# Generated by Django 4.2.15 on 2025-02-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_delete_skillvalidation_alert_status'),
    ]

    operations = [
       
    ]
