# Generated by Django 4.2.15 on 2025-02-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_delete_skillvalidation'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='alert',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost'),
        ),
    ]
