# Generated by Django 4.2.15 on 2025-02-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_delete_skillvalidation_alter_alert_vacancy'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='jobpost',
            name='req_ceo_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='req_finance_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert3', to='jobs.jobpost'),
        ),
    ]
