# Generated by Django 4.2.15 on 2025-02-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0054_scoreboard_scorequestion_scoreresult_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='scorequestion',
            name='level',
            field=models.CharField(default='D', max_length=50),
        ),
    ]
