# Generated by Django 4.2.15 on 2025-02-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0055_delete_skillvalidation_alter_scorequestion_level'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='scorequestion',
            name='max_score',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='scoreresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.scorequestion'),
        ),
    ]
