# Generated by Django 4.2.15 on 2025-02-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0056_delete_skillvalidation_alter_scorequestion_max_score_and_more'),
    ]

    operations = [
     
        migrations.RemoveField(
            model_name='scoreresult',
            name='user',
        ),
        migrations.AddField(
            model_name='scoreresult',
            name='application',
            field=models.ForeignKey(default=77, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication'),
            preserve_default=False,
        ),
    ]
