# Generated by Django 4.2.15 on 2025-02-09 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0057_delete_skillvalidation_remove_scoreresult_user_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='scoreresult',
            name='application',
            field=models.ForeignKey(default=77, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication'),
        ),
    ]
