# Generated by Django 4.2.15 on 2025-02-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0058_delete_skillvalidation_alter_scoreresult_application'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='scoreresult',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication'),
        ),
    ]
