# Generated by Django 4.2.15 on 2025-02-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0059_delete_skillvalidation_alter_scoreresult_application'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='jobapplication',
            name='is_approved',
            field=models.CharField(default='waiting', max_length=50),
        ),
    ]
