# Generated by Django 4.2.15 on 2025-02-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0060_delete_skillvalidation_jobapplication_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewScoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewScoreQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('level', models.CharField(default='E', max_length=50)),
                ('max_score', models.IntegerField(default=4)),
                ('scoreboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='jobs.scoreboard')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewScoreResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.scorequestion')),
                ('scoreboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to='jobs.scoreboard')),
            ],
        ),
       
        migrations.AddField(
            model_name='jobpost',
            name='interview_scoreboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewscoreboard',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_scoreboards', to='jobs.jobpost'),
        ),
    ]
