# Generated by Django 4.2.15 on 2025-02-18 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0063_interviewer_delete_skillvalidation'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='interviewscoreresult',
            name='interviewer',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
