# Generated by Django 4.2.15 on 2025-02-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0065_delete_skillvalidation_interviewer_note_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='interviewer',
            name='score',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
