# Generated by Django 4.2.15 on 2025-02-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0068_delete_skillvalidation_jobpost_is_interviewed'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='jobpost',
            name='is_selected_approved',
            field=models.BooleanField(default=False),
        ),
    ]
