# Generated by Django 4.2.11 on 2024-06-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_backup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='time',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
