# Generated by Django 4.2.15 on 2024-09-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagelist',
            name='reading_proficiency',
        ),
        migrations.RemoveField(
            model_name='languagelist',
            name='writing_proficiency',
        ),
    ]
