# Generated by Django 4.2.15 on 2024-09-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_remove_languagelist_reading_proficiency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NQF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=225)),
            ],
        ),
    ]
