# Generated by Django 4.2.15 on 2024-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerproficiency',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingproficiencylist',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softproficiency',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speakingproficiencylist',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writingproficiencylist',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
